name: corel-env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - cryptography=41.0.2
  - cuda-cudart
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy-base=1.25.2
  - openh264=2.1.1
  - openssl=3.0.10
  - pillow=9.4.0
  - pip=23.2.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.17
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.1
    - chardet==5.2.0
    - charset-normalizer==3.2.0
    - check-shapes==1.1.1
    - cloudpickle==2.2.1
    - cmake==3.27.2
    - corel==0.0.1
    - decorator==5.1.1
    - deprecated==1.2.14
    - dill==0.3.7
    - dm-tree==0.1.8
    - dropstackframe==0.1.0
    - filelock==3.12.2
    - flatbuffers==23.5.26
    - gast==0.4.0
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - gpflow==2.9.0
    - gpflux==0.4.2
    - greenlet==2.0.2
    - grpcio==1.57.0
    - h5py==3.9.0
    - importlib-metadata==6.8.0
    - jax==0.4.14
    - keras==2.12.0
    - lark==1.1.7
    - libclang==16.0.6
    - lit==16.0.6
    - markdown==3.4.4
    - markupsafe==2.1.3
    - ml-dtypes==0.2.0
    - multipledispatch==1.0.0
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.1
    - poli==0.0.1
    - protobuf==4.24.1
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.11.2
    - six==1.16.0
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.1
    - tensorflow==2.12.1
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.33.0
    - tensorflow-probability==0.19.0
    - termcolor==2.3.0
    - trieste==1.2.0
    - triton==2.0.0
    - typing-extensions==4.5.0
    - werkzeug==2.3.7
    - wrapt==1.14.1
    - zipp==3.16.2
