__author__ = 'Simon Bartels'
"""
Question: where actually are the mutations of the successful mutations of mRouge?


"""

# this is the original mRouge sequence
mRouge = "MVSKGEEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSPQFMYGSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLRGTNFPSDGPVMQKKTMGWEACSERMYPEDGALKGEMKMRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNTNTKLDITSHNEDYTIVEQYERNEGRHSTGGMDELYK"

# this mutations are somehow specially PDB prepared. Note for example the missing MVSKG preamble
mRouge_0127 = "EEDNMAIIKEFMRFKTHMEGSVNFHEFEIEGKGEGRPYEGQQTAKLKVTKGGELPFAWDTLSPQFSKAYVRHPAWIYDYSKLSFWEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLRGTNFPSDGPVMQKKTMGWERCSERMYPEDRALKGEMKMWLKLKDEGRYDAEVETTYKAKRPVDLPGAYWTNTKLDITSHRRDYTIVEQYERNEGETSTGRMWELYK"
mRouge_0133 = "EEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILCPQFSKAYGRHPAYIPDYLKLSFPEGFKVERVMNFEDEGVVEVTQDSSLQDGEFIYKVKLRGTRFPSDGPVMQKKTMRWEPCSERMYREDGALKGEMKMRLKLKDGFHYPAEVKTTYKAKKPVRLPGAYNTMTKLDIFSHKERYPIVEQFERNEGRHSTGGMDELYK"
mRouge_0137 = "EEDNMAIMKEFMRFKTHMLGSVNGYEFEILGEGEGRPYEGTQTAKLKVTKGGPLNFAWDILSPQFSKAYVKHPYDIPDYLKLSFPEGFKWERVMNFEDRGVVTVTQFSSLQKGEFIYKVKLRGTNFTPDGPVMQKKTMGWERCSERIYPEDRALKGRMKMRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYKVNTELMITSHNRDYTIVEQYERNEGRHSTGRMDELRK"

mRouge127_rec = "MVSKG" + "EEDNMAIIKEFMRFKTHMEGSVNFHEFEIEGKGEGRPYEGQQTAKLKVTKGGELPFAWDTLSPQF" + "MYG" + "SKAYVRHPAWIYDYSKLSFWEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLRGTNFPSDGPVMQKKTMGWERCSERMYPEDRALKGEMKMWLKLKDEGRYDAEVETTYKAKRPVDLPGAYWTNTKLDITSHRRDYTIVEQYERNEGETSTGRMWELYK"

char_to_int = {chr(i): i-65 for i in range(65, 65+26)}

import numpy as np
def to_np_indices(seq):
    return np.array([char_to_int[a] for a in seq])
mRouge_ = to_np_indices(mRouge)
mRouge127_ = to_np_indices(mRouge127_rec)

diff = mRouge_ - mRouge127_
print(diff)
print(np.where(diff!=0))